### ISSUE TITLE
Publication checklist

### ISSUE THREAD

**Issue by SichangHe** [FedCampus/FedKit_demo_paper#13]
- [x] #12 
  - [x] When you are done with the revision, please print out your abstract and carefully proofread it. Review formatting requirements can be found at: [https://www.ieee.org/conferences_events/conferences/publishing/templates.html](https://urldefense.com/v3/__https://www.ieee.org/conferences_events/conferences/publishing/templates.html__;!!OToaGQ!uQxs3qlXPy6qgGDoyg5BIEIsaO6dfd2HTW829u_rHmJBLcFb2zfN7menMWnRK_sMiKEluHAUry8OXrAB15a1I9UJQ1q25j2QLsQS1A$)
  @Beilong-Tang, was that the template that you pulled?
  - [x] To submit your final abstract, please go to EDAS, click on the “My Papers” button, and then upload your abstract on the link provided. The registration code is “INF” + confirmation number of your registration. The author list in the PDF file should exactly conform with that in EDAS; otherwise, the abstract will be removed from the program. If you experience any problems during the upload process of your abstract on EDAS, please contact [help@edas-help.com](mailto:help@edas-help.com).
  - [x] IEEE copyright form
- [x] register for INFOCOM
  @Beilong-Tang, do you want to go? Ask Prof Luo to see how travel funding works, etc.
  For Demo/Poster registration, please go to the Registration page of the IEEE INFOCOM 2024 website [https://infocom2024.ieee-infocom.org/registration](https://urldefense.com/v3/__https://infocom2024.ieee-infocom.org/registration__;!!OToaGQ!uQxs3qlXPy6qgGDoyg5BIEIsaO6dfd2HTW829u_rHmJBLcFb2zfN7menMWnRK_sMiKEluHAUry8OXrAB15a1I9UJQ1q25j06H0UNow$) and follow the instructions. After completing your registration, you will receive an email with your registration confirmation number. Write this number down; you will need to use it to upload your abstract into EDAS.
  - [ ] Present the demo
- [x] Use IEEE PDF eXpress to check if your paper is Xplore compatible. The PDF eXpress website can be found at [https://ieee-pdf-express.org/](https://urldefense.com/v3/__https://ieee-pdf-express.org/__;!!OToaGQ!uQxs3qlXPy6qgGDoyg5BIEIsaO6dfd2HTW829u_rHmJBLcFb2zfN7menMWnRK_sMiKEluHAUry8OXrAB15a1I9UJQ1q25j0HGwp76A$). The conference ID for INFOCOM 2024 Demo is 61880.

**Comment by Beilong-Tang** [comment]
#12 
I did not know if that is exactly the original template I followed, but they should follow the same format.

**register for INFOCOM**
I would like to go with you if I can. Have you talked with Prof Luo about this?

For demo presentation, how do we address the issue that the IOS data is actually a bit *fake* ?

Please let me know if there is any task I can help.

**Comment by SichangHe** [comment]
> #12 I did not know if that is exactly the original template I followed, but they should follow the same format.

I guess we will see when we put it into the IEEE PDF eXpress.

> **register for INFOCOM** I would like to go with you if I can. Have you talked with Prof Luo about this?

No, I haven't. It is still in the middle of the Spring Festival break and I am still sorting out the camera-ready version. You can ask him now if you want, though.

> For demo presentation, how do we address the issue that the IOS data is no longer reproducible ?

We will only live demo the example app, not the FedCampus App. For the FedCampus App, I have some vague plans that we can talk about in private.

> Please let me know if there is any task I can help.

I guess #12.

**Comment by SichangHe** [comment]
<details><summary>I guess this means it is Xplore-compatible.</summary>

![image](https://github.com/FedCampus/FedKit_demo_paper/assets/84777573/342e3197-b13f-4ffd-8593-67aca0a87947)

</details>

**Comment by SichangHe** [comment]
<details><summary>The new version is also Xplore-compatible.</summary>

![image](https://github.com/FedCampus/FedKit_demo_paper/assets/84777573/01f07745-0bb6-45c1-8d02-2c4f1e759744)

</details>
